name: Create HTML5 Zip
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        path: 'scripts'
        filename: 'scripts.html5.zip'
        custom: '-r -j -P ${{ secrets.ZipPassword }}'
    
    - name: Upload Zip Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 'scripts.html5'
        path: 'scripts.html5.zip'
